import { StyleSheet } from 'react-native';
//import { Roboto_400Regular} from '@expo-google-fonts/roboto';

const styles = StyleSheet.create({
    root:{
        backgroundColor:"#F9F9F9",
        flex:1,
        flexDirection:"column",
        },
    imageContainer:{
        flex:1,
        width:'100%',
        borderRadius:30,
    },
    serviceName:{
        flex:1,
        flexBasis:"70%",
    },
    image:{
        height:350,
        borderRadius:30,

    },
    profileContainer:{
        paddingHorizontal:38,
        marginTop:20,
    },
    profileHeader:{
        width:"100%",
        justifyContent:"space-between",
        flexDirection:"row",
        alignItems:"center",
    },
    userName:{
        color:"black",
        borderRadius:30,
        fontFamily:"Roboto",
        fontSize:20,
        fontWeight:"bold",
    },
    editable:{
        borderRadius:30,
        paddingVertical:10,
        paddingHorizontal:20,
        width:300,
        fontFamily:"Roboto",
        fontSize:20,
        fontWeight:"bold",
        borderColor:"black",
        borderWidth:1,
    },  
    location:{
        alignItems:"center",
        width:'100%',
        flexDirection:"row",
    },
    locationContainer:{
        flex:1,
        width:'100%',
        alignItems:"center",
        flexDirection:"row",
        marginTop:10
    },
    locationText:{
        marginLeft:10,
    },
    editPicture:{
        position:"absolute",
        borderRadius:50,
        backgroundColor:"#0A61E1",
        padding:15,
        bottom:-30,
        right:20,
    },
    iconContainer:{
        padding:10,
        backgroundColor:"#0A61E1",
        borderRadius:50,
    },
    iconsContainer:{
        flexBasis:"30%",
        flexDirection:"row",
        justifyContent:"space-between",
    },
    description:{
        fontFamily:"Roboto",
        marginTop:15,
    },
    hours:{
        marginTop:15,
        fontFamily:"Roboto",
        fontSize:15,
        fontWeight:"bold",
        marginBottom:10
    },
    workingHours:{
        fontFamily:"Roboto",
    }
     });

export default styles;